'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Tenants_Edit

    '''<summary>
    '''HeadingLiteral control.
    '''</summary>
    Protected WithEvents HeadingLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''ErrorPanel control.
    '''</summary>
    Protected WithEvents ErrorPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ErrorLiteral control.
    '''</summary>
    Protected WithEvents ErrorLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''TenantIdBox control.
    '''</summary>
    Protected WithEvents TenantIdBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TenantNameBox control.
    '''</summary>
    Protected WithEvents TenantNameBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DatabaseNameBox control.
    '''</summary>
    Protected WithEvents DatabaseNameBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DatabaseServerBox control.
    '''</summary>
    Protected WithEvents DatabaseServerBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DatabaseUserBox control.
    '''</summary>
    Protected WithEvents DatabaseUserBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DatabasePasswordBox control.
    '''</summary>
    Protected WithEvents DatabasePasswordBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''PasswordRequired control.
    '''</summary>
    Protected WithEvents PasswordRequired As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''PasswordHintLiteral control.
    '''</summary>
    Protected WithEvents PasswordHintLiteral As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''SaveButton control.
    '''</summary>
    Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button
End Class
